---
kind: Namespace
apiVersion: v1
metadata:
  name: cr-connect-bot
  labels:
    name: cr-connect-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cr-connect-rabbitmq-distributed-leader-deployment
    namespace: cr-connect-bot
    labels:
        app: cr-connect-rabbitmq-distributed-leader-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
         app: cr-connect-rabbitmq-distributed-leader
    template:
      metadata:
         name: cr-connect-rabbitmq-distributed-leader
         namespace: cr-connect-bot
         labels:
            app: cr-connect-rabbitmq-distributed-leader
            department: bots
      spec:
        containers:
          - name: cr-connect-rabbitmq-distributed-leader-container
            image: ghcr.io/theyellow/connect:master
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: cr-connect-bot-secrets
            ports:
              - containerPort: 8080
            command: [ "java", "-Xmx300m", "-cp", "/cr-connect-bot.jar", "discord4j.connect.rabbitmq.shared.ExampleRabbitDistributedCacheLeader" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cr-connect-rabbitmq-distributed-worker-deployment
    namespace: cr-connect-bot
    labels:
        app: cr-connect-rabbitmq-distributed-worker-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
         app: cr-connect-rabbitmq-distributed-worker
    template:
      metadata:
         name: cr-connect-rabbitmq-distributed-worker
         namespace: cr-connect-bot
         labels:
           app: cr-connect-rabbitmq-distributed-worker
           department: bots
      spec:
        containers:
          - name: cr-connect-rabbitmq-distributed-worker-container
            image: ghcr.io/theyellow/connect:master
            imagePullPolicy: Always
            envFrom:
             - secretRef:
                 name: cr-connect-bot-secrets
            ports:
              - containerPort: 8080
            command: [ "java", "-Xmx300m", "-cp", "/cr-connect-bot.jar", "discord4j.connect.rabbitmq.shared.ExampleRabbitDistributedCacheWorker" ]
---
