---
kind: Namespace
apiVersion: v1
metadata:
  name: cr-connect-bot
  labels:
    name: cr-connect-bot
---
apiVersion: v1
kind: Service
metadata:
  name: cr-connect-bot-redis
  namespace: cr-connect-bot
spec:
  selector:
    app: cr-connect-redis
    department: bots
  type: NodePort
  ports:
    - port: 6379
      nodePort: 31379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cr-connect-bot-redis-config
  namespace: cr-connect-bot
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-connect
  namespace: cr-connect-bot
  labels:
      app: cr-connect-redis
      department: bots
spec:
  containers:
    - name: redis-connect
      image: redis:5.0.4
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: cr-connect-bot-redis-config
        items:
          - key: redis-config
            path: redis.conf
---
